# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94aecb8202b2d9810b37c8f4482c71c3a9a3671f206deb8b525f82eb38ebb22b22d0b9f76d493166807ae5f85fba0cc9eb119a15feea95ee9d972bfa62e6cf11

test:
  secret_key_base: c4a7900d04499245325bab36e058e48b8eb5ea166263eb3092e178d1769c61ec294948e901cca0adeaff3bc5205a0b59386800c619f76117e624d2413cef74de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
